version: '3.8'

services:
  flow2api:
    build: .
    container_name: flow2api
    ports:
      - "8002:8000"
    volumes:
      - /data/coolify/applications/nk8k0wgs0o4w40swkok840ok/data:/app/data
      - /data/coolify/applications/nk8k0wgs0o4w40swkok840ok/config:/app/config
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - warp

  warp:
    image: caomingjun/warp
    container_name: warp
    restart: always
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "1082:1080"
    environment:
      - WARP_SLEEP=2
    cap_add:
      - MKNOD
      - AUDIT_WRITE
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - /data/coolify/applications/nk8k0wgs0o4w40swkok840ok/data:/var/lib/cloudflare-warp
